---
- name: Download repo key
  ansible.builtin.shell:
    cmd: "curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor --output {{ nodejs_keyring }}"
    creates: "{{ nodejs_keyring }}"
  tags:
    - nodejs

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ nodejs_arch }} signed-by={{ nodejs_keyring }}] https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    filename: nodesource
    update_cache: True
    state: present
  tags:
    - nodejs

- name: Install required packages
  loop: "{{ nodejs_packages }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - nodejs

...
